### ISSUE TITLE
Make the unit-tests prefix adjustable

### ISSUE THREAD

**Issue by passsy** [grahamsmith/dart-test#1]
https://github.com/grahamsmith/dart-test/blob/cc3c5b03ca500a32408aa384c52b04bef23181c3/src/main/kotlin/com/github/grahamsmith/darttest/actions/ActionHelper.kt#L28

The default path prefix `/test/unit-test/` is rather uncommon. I did not expect the `unit-test` folder and would like it to be gone, or at least make it adjustable.

**Comment by grahamsmith** [comment]
Check the README Future Work section 😉

**Comment by grahamsmith** [comment]
I would be interested to know what is usual in projects. How are tests split up? Or aren't they? 

Do UI, unit and integration (etc) get lumped together. Happy for input here.

**Comment by passsy** [comment]
I've never seen unit and widget tests split up in a Flutter project. They all are pure Dart and run on the DartVM. I'm not saying it doesn't make sense, just that I've never seen it and I can't think of cases where I only want to execute one kind of test. I usually run all or single files.

The only distinction should be which external services are involved. There is `/integration-test` for flutter driver tests. And I've seen projects having custom `/e2e-test` folders to run tests against real systems.

**Comment by grahamsmith** [comment]
![Screenshot 2021-11-02 at 18 36 41](https://user-images.githubusercontent.com/1571527/139924814-75ad2552-3c40-49bb-b06e-c1205c2224d4.png)

@passsy - sorry for the looooong delay on this. Between getting married and a few other huge life events its been a bit crazy.

Above is a screenshot of the sort of thing I was thinking. Thoughts?

**Comment by ash0080** [comment]
Any updates?

**Comment by grahamsmith** [comment]
@ash0080 - ah I wasn't sure anyone was interested as had no feedback 😅

Is the screenshot above what is wanted?

**Comment by ash0080** [comment]
> @ash0080 - ah I wasn't sure anyone was interested as had no feedback 😅
> 
> Is the screenshot above what is wanted?

Yes, can this version be released?

**Comment by grahamsmith** [comment]
@ash0080 I have removed the unit-test prefix in the pending release.

I'll have a go at the customisation options after I've added widget test support.
