### ISSUE TITLE
Not compatible with 2022.3.2

### ISSUE THREAD

**Issue by atreeon** [grahamsmith/dart-test#10]
This is just what I need! I tried to install it but was told it isn't comatible.  I spent 15mins hoping I could understand how to recompile to a new version but I'm not a Java developer.  Any plans to update and release?  Thanks!

**Comment by grahamsmith** [comment]
I really should. Jetbrains changed the template this is based on and I have not had time to work out the diff is. I've been sick with COVID so will get some time shortly to fix this up.

**Comment by atreeon** [comment]
ah get well and look forward to the new release :)

**Comment by grahamsmith** [comment]
This wil be fixed when https://github.com/grahamsmith/dart-test/pull/11 is released
