### ISSUE TITLE
Not compatible with IntelliJ IDEA 2024.1

### ISSUE THREAD

**Issue by atreeon** [grahamsmith/dart-test#19]
This looks like the plugin I need!

Is it easy to update to be compatible to 2024.1?

**Comment by grahamsmith** [comment]
Yes it should be. I can update or you can look at previous commits to keep it upto date and open a PR. Should be simple enough.

**Comment by atreeon** [comment]
Done!  Thanks, all working (first time I've looked at an intellij plugin)

**Comment by jihadnaji** [comment]
@grahamsmith could you please update the plugin to be compatible with the newest Android Studio releases? I would be happy to contribute a PR, but I have never worked with plugins code.

**Comment by grahamsmith** [comment]
@atreeon - I FINALLY got around to fixing this. I shall pop you on the README contributors list.

**Comment by atreeon** [comment]
Thanks!
